CREATE VIEW AGENT_IZD_ZAK_NEKR AS
SELECT count(izd_zaposleni_zapid) as Izdavanje_ugovora, count(zak_zaposleni_zapid) as Zakup_ugovora, zak_zaposleni_zapid, ZAPIME, ZAPPRZ
FROM UGOVOR_O_IZDAVANJU
INNER JOIN UGOVOR_O_ZAKUPU ON UGOVOR_O_IZDAVANJU.IZD_NEKRETNINA_NID = UGOVOR_O_ZAKUPU.ZAK_NEKRETNINA_NID
INNER JOIN ZAPOSLENI ON UGOVOR_O_ZAKUPU.ZAK_ZAPOSLENI_ZAPID = ZAPOSLENI.ZAPID
WHERE izd_zaposleni_zapid=zak_zaposleni_zapid AND zak_zaposleni_zapid = ZAPOSLENI.ZAPID
group by zak_zaposleni_zapid, ZAPOSLENI.ZAPIME, ZAPOSLENI.ZAPPRZ;

CREATE VIEW ZAKUPODAVCI_PO_DRZAVAMA AS
SELECT COUNT(KLIJENT.KMBR) AS BR_PONAVLJANJA_VLASNIKA, KLIJENT.GRAD_DID
FROM KLIJENT
INNER JOIN UGOVOR_O_IZDAVANJU ON KLIJENT.KID = UGOVOR_O_IZDAVANJU.IZD_VLASNIK_KID
GROUP BY KLIJENT.GRAD_DID
HAVING COUNT(KLIJENT.KMBR) > 0
ORDER BY COUNT(KLIJENT.KMBR) DESC;

CREATE VIEW SVI_UGOVORI AS
SELECT "UOIZ_ID","UOIZDAT","UOIZOPIS","IZD_NEKRETNINA_NID","IZD_VLASNIK_KID","IZD_ZAPOSLENI_ZAPID","UOZ_ID","UOZUGDAT","UOZOPIS","UOZUGKIR","UOZUGDEP","UOZUGPROV","UOZUGTRAJGOD","ZAK_VALUTA_VALID","ZAK_ZAPOSLENI_ZAPID","ZAKUPAC_KID","ZAK_OGLAS_O_ID","ZAK_NEKRETNINA_NID","ZAK_VLASNIK_KID"
FROM UGOVOR_O_IZDAVANJU
INNER JOIN UGOVOR_O_ZAKUPU ON UGOVOR_O_IZDAVANJU.IZD_NEKRETNINA_NID = UGOVOR_O_ZAKUPU.ZAK_NEKRETNINA_NID;


CREATE VIEW SVI_VLASNICI AS
SELECT "KID","KMBR","KBRLK","KVRSTA","KIME","KPRZ","KADR","KTEL","KEMAIL","KULOGA","GRAD_GID","GRAD_DID","UOIZ_ID","UOIZDAT","UOIZOPIS","IZD_NEKRETNINA_NID","IZD_VLASNIK_KID","IZD_ZAPOSLENI_ZAPID"
FROM KLIJENT
INNER JOIN UGOVOR_O_IZDAVANJU ON KLIJENT.KID = UGOVOR_O_IZDAVANJU.IZD_VLASNIK_KID;